billing/urls.py
from django.urls import path

from .views import (bill_costing,
                    bill_sorter,
                    bill_listing,
                    bill_view,
                    bill_paid,
                    create_receipt
                    )

urlpatterns = [
    path('', bill_costing, name = "bill-costing"),
    path('create_bills/', bill_sorter, name = "create_bills"),
    path('create_receipt/<int:bill_id>/', create_receipt, name = "create_receipt"),
    path('bill_list/', bill_listing, name = "bill_list"),
    path('bill_view/<int:id>/', bill_view, name = "bill_view"),
    path('bill_paid/<int:id>/<str:status>', bill_paid, name = "bill_paid"),
]

society/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls import url
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('members.urls')),
    path('billing/', include('billing.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

billing/models.py
from django.db import models

from members.models import Flat


class BillDetails(models.Model):
    flat_type       = models.CharField(max_length =1, help_text ="Your Choices are 1, 2, 3.", default="3")
    municipal_tax   = models.DecimalField(max_digits=10, decimal_places=2, help_text = "Taxes Levied by BMC")
    maintenance     = models.DecimalField(max_digits=10, decimal_places=2, help_text = "Maintenance Charges")
    water_charges   = models.DecimalField(max_digits=10, decimal_places=2, help_text = "Water Costs")
    parking_charges = models.DecimalField(max_digits=10, decimal_places=2, help_text = "Car/Scooter/Stilt")
    sinking_fund    = models.DecimalField(max_digits=10, decimal_places=2, help_text = "Sinking Fund")
    building_repair = models.DecimalField(max_digits=10, decimal_places=2, help_text = "Fund for Building Repairs")
    elec_ins_chgs   = models.DecimalField("Electricity Insurance Charges", max_digits=10,
                                            decimal_places=2,
                                            help_text = "Electricity Insurance"
                                        )
    
    class Meta:
        verbose_name_plural = "Billing Details"

    def __str__(self):
        return ("The Initial Costs for Flat type: {}").format(self.flat_type)
    
    def maintenance_total(self):
        return(self.maintenance + 
                self.water_charges +
                self.parking_charges + 
                self.sinking_fund + 
                self.building_repair + 
                self.elec_ins_chgs
                )




class FlatBill(models.Model):
    flat_name       = models.ForeignKey(Flat, on_delete=models.CASCADE)
    bill_date       = models.DateField("Bill Date", auto_now_add=True)
    municipal_tax   = models.DecimalField(max_digits=10, decimal_places=2, help_text = "Taxes Levied by BMC")
    maintenance     = models.DecimalField(max_digits=10, decimal_places=2, help_text = "Maintenance Charges")
    water_charges   = models.DecimalField(max_digits=10, decimal_places=2, help_text = "Water Costs")
    parking_charges = models.DecimalField(max_digits=10, decimal_places=2, help_text = "Car/Scooter/Stilt")
    sinking_fund    = models.DecimalField(max_digits=10, decimal_places=2, help_text = "Sinking Fund")
    building_repair = models.DecimalField(max_digits=10, decimal_places=2, help_text = "Fund for Building Repairs")
    is_paid         = models.BooleanField(default=False)
    elec_ins_chgs   = models.DecimalField("Electricity Insurance Charges", max_digits=10,
                                            decimal_places=2,
                                            help_text = "Electricity Insurance"
                                        )
    noc_charges     = models.DecimalField("N.O.C. Charges", max_digits=10, decimal_places=2, 
                                         help_text = "Non Occupancy Charges",
                                         default = 0,
                                         )
    add_item_name_1 = models.CharField("Additional Items e.g. Building Maintenance",
                                        max_length=100, blank=True )
    add_item_name_2 = models.CharField("Additional Items e.g. Emergency_fund",
                                        max_length=100, blank=True )
    add_item_amt_1  = models.DecimalField(default = 0, max_digits=10, decimal_places=2, help_text = "Amount for Additional Item 1")
    add_item_amt_2  = models.DecimalField(default = 0, max_digits=10, decimal_places=2, help_text = "Amount for Additional Item 2")                                        
    
    
    def __str__(self):
        return ("Bill for Flat: {} Dated : {}".format(self.flat_name, self.bill_date))

    def total(self):
        return(self.municipal_tax + 
                self.maintenance + 
                self.water_charges +
                self.parking_charges + 
                self.sinking_fund + 
                self.building_repair + 
                self.elec_ins_chgs + 
                self.noc_charges + 
                self.add_item_amt_1 + 
                self.add_item_amt_2
                )
    
# def get_total(instance):
#     return instance.total()

class Receipt(models.Model):
    related_bill = models.OneToOneField(FlatBill, on_delete=models.CASCADE)
    paid_on = models.DateField()
    payment_mode = models.CharField(max_length=200, help_text = "Cheque, Bank Transfer etc.")
    drawn_on = models.CharField(max_length=250, help_text="Financial institution received from.")
    transaction_no = models.CharField(max_length=250, help_text="Cheque Number or Bank Transfer Number.")
    received_amount = models.DecimalField(max_digits=25, decimal_places=2, help_text="Amount Received from Member.")

    def __str__(self):
        return ("Receipt for {} paid on {} for the amount Rs. {}.".format(self.related_bill.flat_name, 
                                                                          self.paid_on,
                                                                          self.received_amount)
                )

billing/forms.py
from django.forms import ModelForm

from .models import  FlatBill, Receipt

class ReceiptForm (ModelForm):
    class Meta:
        model = Receipt
        # fields = '__all__'
        exclude = ['related_bill']
        # fields = ['paid_on','payment_mode', 'drawn_on', 'transaction_no', 'received_amount']


class FlatBillForm(ModelForm):
    class Meta:
        model = FlatBill
        fields = ['is_paid']

billing/views.py
from datetime import datetime

from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse, reverse_lazy

from .forms import ReceiptForm, FlatBillForm
from .models import BillDetails, FlatBill, Receipt
from .utilities import create_flat_bills

from members.models import Flat


def bill_costing(request):
    #''' This Function sends out a list of all flat types in a building and 
    # and then sends it to a view. The types of flats at the moment
    # are type 1,2 and 3'''
    initial_amounts = BillDetails.objects.all().order_by('flat_type')
    context = {'initial_amounts': initial_amounts}
    return render(request, 'billing/initial_bill.html', context)




def bill_sorter(request):
    #''''This function generates all the bills for each flat depending
    # on the flat type from the initial values provided to the model.
    # It uses a helper function from the utilities module
    # called create_flat_bills and takes 2 arguments.
    # flat object and a filtered BillDetails object filtered on the 3 digit
    # of the flat number. '''
    date_string = datetime.now()
    error_flats = ""
    for flat in Flat.objects.all():
        bill_type = BillDetails.objects.get(flat_type = flat.flat_number[2])
        #'''Now we will check if bill from present month for that flat is already the flat in question
        # check_bill is filtered by flat, year and month and then using exists() from django we check 
        # if the bill exists. If it does we send a message'''
        check_bill = FlatBill.objects.filter(flat_name = flat).filter(bill_date__year =date_string.year)
        if check_bill.filter(bill_date__month =date_string.month).exists():
            error_flats+= (flat.__str__() + ", ")
        else:
            create_flat_bills(flat, bill_type)
    #'''Below we check to see if our previous error checking has resulted in a string of flats.
    # If it hasn't then we don't send an error message by setting the variable to none.
    # we only send an error message variable if there is a string with error flats'''
    if not error_flats =="":
        error_message = "There already exist bills for the period of {} {} for flats ".format (date_string.strftime("%B"), date_string.year)
        error_message+= error_flats
    else:
        error_message = None
    messages.add_message(request, messages.INFO, error_message)            
    return redirect('bill_list')



def bill_listing(request):
    #''' This function just gives out a list of all the bills created so far.
    # It will soon be filtered by month and then year'''
    bills = FlatBill.objects.all()
    context = {'bills': bills}
    
    return render(request, 'billing/bill_list.html', context)

def bill_view(request, id):
        #'''This function just gives details of the bill asked for taking
    # one parameter. The bill pk or id. '''
    bill = get_object_or_404(FlatBill, id = id)
    #'''We also included the form for the receipt model and added some logic in the view template that 
    # lets you include either the receipt form if receipt does not exist or the receipt if it exists '''
    receipt_form = ReceiptForm(request.POST or None, initial={'received_amount':bill.total()})
    if receipt_form.is_valid():
        instance = receipt_form.save(commit=False)
        instance.related_bill = bill
        instance.save()
    context = {'bill':bill, 'receipt_form':receipt_form}
    return render (request, 'billing/bill_view.html', context)

def bill_paid(request, id, status):
    bill = FlatBill.objects.get(id=id)
    bill.is_paid = True
    bill.save()
    print (status)
    return HttpResponseRedirect(reverse('bill_view', kwargs = {'id':id}))


def create_receipt(request, bill_id):
    bill = FlatBill.objects.get(id=bill_id)
    edit = False
    if Receipt.objects.filter(related_bill=bill).exists():
        edit = True
        receipt_instance = bill.receipt
        print (receipt_instance)
        receipt_form = ReceiptForm(request.POST or None, instance=receipt_instance)
        if receipt_form.is_valid():
            receipt_form.save()
            return HttpResponseRedirect(reverse('bill_view', kwargs = {'id':bill.id}))
    else:
        receipt_form = ReceiptForm(request.POST or None,
                              initial = {'received_amount':bill.total() }
                              )
        if receipt_form.is_valid():
            instance = receipt_form.save(commit = False)
            instance.related_bill = bill
            bill.is_paid = True
            bill.save()
            instance.save()
            return HttpResponseRedirect(reverse('bill_view', kwargs = {'id':bill.id}))
    return render (request, 'billing/receipt_form.html', {'form': receipt_form, 'edit':edit})

society/templates/billing/bill_list.html
{% extends 'index1.html' %}

{% block content %}
<br>



    {% if messages %}
        {% for message in messages%}
            {{message}}
        {% endfor %}

    {% endif %}

    {% if bills %}
    <br>
    <p><strong>All Bills: </strong></p>
    <table class="table table-bordered table-hover">
            <thead class="thead-light">
                    <tr>
                        <th>Flat No.</th>
                        <th>Bill Amount</th>
                        <th>Bill Date</th>
                        <th>Status</th>
                    </tr>
            </thead>
        {% for bill in bills %}
        
            <tr>
                <td><strong>{{bill.flat_name}}</strong></td>
                <td><strong>{{bill.total}}</strong></td> 
                <td><a  href = "{% url 'bill_view' bill.id %}"> {{bill.bill_date|date:"j M Y"}}</a></td>
                {% if bill.is_paid %}
                <td style="color:green">Receipt no: {{bill.receipt.id}}</td>
                {% else %}
                <td style="color:red" >OUTSTANDING</td>
                {% endif %}
            </tr>

        {% endfor %}
    {% else %}
        No Bills to Show
    {% endif %}
    </table>



<br>      
<a  href = "{% url 'create_bills' %}" >
    <i class="material-icons">add</i>Add
</a>

{% endblock content %}

society/templates/billing/bill_view.html
{% extends 'index1.html' %}

{% block content %}
    <div>
        
        <table style="width:100%" class="bordered">
            <tr> 
                <th><h4>Flat : {{bill.flat_name}} </h4></th>
                <th><h5>Bill Date: {{bill.bill_date|date:"j M Y"}}</h5></th>
            </tr>
            <tr>
                <th>{{bill.flat_name.guest}}</th>
                <th><strong>Bill Month: </strong>{{bill.bill_date|date:"M Y"}}</th>
            </tr>
            <tr>
                {% if not bill.is_paid %}
                    <td style="color:red">Outstanding</td>
                    <td ><a href  ="{% url 'create_receipt' bill.id %}" style='color:red'><i class="material-icons">add</i> Create Receipt.</a></td>
                {% else %}
                    <td style="color:green">Paid: Receipt no. {{bill.receipt.id}}</td>
                    <td ><a href  ="{% url 'create_receipt' bill.id %}" style='color:green'><i class="material-icons">edit</i> Edit Receipt.</a></td>

                {% endif %}
            </tr>            
            <tr>
                
            </tr>
        </table>
            <table style="width:100%" class="bordered">
                <tr>
                <th style="width:70%" class="center-align bordered">Particulars</th>
                <th class="right-align">Amount (Rs.)</th> 
                </tr>
                
                <tr>
                    <td>Municipal Tax</td>
                    <td class="right-align">{{bill.municipal_tax}}</td> 
                </tr>
                
                </tr>
                    <tr>
                    <td>Maintenance Charges</td>
                    <td class="right-align">{{bill.maintenance}}</td> 
                </tr>

                <tr>
                   <td>Water Charges</td>
                   <td class="right-align">{{bill.water_charges}}</td> 
                </tr>
                
                <tr>
                    <td>Parking Charges - Car/Scooter/Stilt</td>
                    <td class="right-align">{{bill.parking_charges}}</td> 
                </tr>

                <tr>
                    <td>Sinking Fund</td>
                    <td class="right-align">{{bill.sinking_fund}}</td> 
                </tr>

                <tr>
                        <td>Building Repair Fund</td>
                        <td class="right-align">{{bill.building_repair}}</td> 
                </tr>

                <tr>
                        <td>Electricity Insurance Charges</td>
                        <td class="right-align">{{bill.elec_ins_chgs}}</td> 
                </tr>

                <tr>
                        <td>Non Occupancy Charges</td>
                        <td class="right-align">{{bill.noc_charges}}</td> 
                </tr>

                <tr>
                        <td>Additional Items</td>
                        <td class="right-align">{{bill.add_item_amt_1}}</td> 
                </tr>

                <tr>
                        <td>Additional Items</td>
                        <td class="right-align">{{bill.add_item_amt_2}}</td> 
                </tr>

                <tr>
                        <td class="right-align"><strong>TOTAL</strong></td>
                        <td class="right-align"><strong>{{bill.total}}</strong></td> 
                </tr>

            </table>
        

        </div>
    
        {% if bill.receipt %}
            
            <div style="border: 1px solid black; padding:5px 10px 5px 10px;">
                <br>
                <div style="font-weight:bold; font-size:30px ;">
                    RECEIPT
                   
                    <div style="font-weight:medium; font-size:20px ;">
                        <strong>Paid on: </strong>{{bill.receipt.paid_on}}<br>
                        <hr>
                        <strong>Paid by: </strong>{{bill.receipt.payment_mode}} drawn on {{bill.receipt.drawn_on}} vide transaction {{bill.receipt.transaction_no}}.<br>
                    </div>
                    <h5>AMOUNT: {{bill.receipt.received_amount}}</h5>
                </div> 
            </div>

        {% endif %}

    
{% endblock content %}

society/templates/billing/initial_bill.html
{% extends 'index1.html' %}

{% block content %} 

{% for initial in initial_amounts %}

<ul class="collection with-header">
    <li class="collection-header"><h4>Initials Amounts for Flat Type {{initial.flat_type}} </h4></li>
    <li class="collection-item"><div>Municipal Tax <span class="secondary-content">{{initial.municipal_tax}} </span></div></li>
    <li class="collection-item"><div>Maintenance Charges <span class="secondary-content">{{initial.maintenance}} </span></div></li>
    <li class="collection-item"><div>Water Charges <span class="secondary-content">{{initial.water_charges}} </span></div></li>
    <li class="collection-item"><div>Parking Charges - Car/Scooter/Stilt <span class="secondary-content">{{initial.parking_charges}} </span></div></li>
    <li class="collection-item"><div>Sinking Fund <span class="secondary-content">{{initial.sinking_fund}} </span></div></li>
    <li class="collection-item"><div>Building Repair Fund <span class="secondary-content">{{initial.building_repair}} </span></div></li>
    <li class="collection-item"><div>Electricit Insurance Charges <span class="secondary-content">{{initial.elec_ins_chgs}} </span></div></li>
    
  </ul>
        
        
  {% endfor %}


{% endblock content %}

society/templates/billing/receipt_form.html
{% extends 'index1.html' %}

{% block content %}
{# Load the tag library #}
{% load bootstrap4 %}


        <div class="container">
                <form method="POST" action="">
                    {% csrf_token %} 
                    {% bootstrap_form form %}
                    {% bootstrap_form_errors form %}
                        
                    {% if not edit %}
                    <button class="btn btn-danger" type="submit">Create</button>
                    {% else %}
                    <button class="btn btn-success" type="submit">Update</button>
                    {% endif %}
                </form>
        </div>
{% endblock content %}

society/templates/billing/test-form.html
<html>
    <head>
            <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <title>Express Apartments |  Members </title>
    </head>
    <body>

    <div class="container">
                   
                   
                           
            <nav class="navbar navbar-expand-lg navbar-light bg-info">  
                   
                <a href="/" class="navbar-brand text-light">Logo</a>
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item  "><a class="nav-link text-light" href="/">Home</a></li>
                        <li class="nav-item "><a class="nav-link text-light" href="/add/">Add</a></li>
                        <li class="nav-item "><a class="nav-link text-light" href="/flats/">Flats</a></li>
                        <li class="nav-item "><a class="nav-link text-light" href="/billing/bill_list/">List Bills</a></li>
                    </ul>

                    <ul class="navbar-nav ml-auto">
                            <li class="nav-item  "><a class="nav-link text-light" href="#">Sign-in</a></li>
                            <li class="nav-item "><a class="nav-link text-light" href="#">Login</a></li>
                    </ul>
            </nav>            
        <div class="row">            
            <div class="col-6 col-md-4 " >
                <br>
                <span class="text-right ">Content on the side</span>


            </div>            
            <div class="col-12 col-md-8 ">                
                    <div>
                        <br>
                        <strong>Bill Date: </strong>15 Feb 2018<br>
                        <strong>Flat : </strong>303 A<br>
                        Maya Handa<br><br>
                            <table class="table table-bordered">
                                <tr class="table-secondary">
                                <th style="width:70%" scope="col">Particulars</th>
                                <th class="text-right" scope="col">Amount (Rs.)</th> 
                                </tr>
                                
                                <tr>
                                    <td>Municipal Tax</td>
                                    <td class="text-right">2036.00</td> 
                                </tr>
                                
                                </tr>
                                    <tr>
                                    <td>Maintenance Charges</td>
                                    <td class="text-right">1005.00</td> 
                                </tr>
                
                                <tr>
                                <td>Water Charges</td>
                                <td class="text-right">415.00</td> 
                                </tr>
                                
                                <tr>
                                    <td>Parking Charges - Car/Scooter/Stilt</td>
                                    <td class="text-right">100.00</td> 
                                </tr>
                
                                <tr>
                                    <td>Sinking Fund</td>
                                    <td class="text-right">133.00</td> 
                                </tr>
                
                                <tr>
                                        <td>Building Repair Fund</td>
                                        <td class="text-right">1500.00</td> 
                                </tr>
                
                                <tr>
                                        <td>Electricity Insurance Charges</td>
                                        <td class="text-right">610.00</td> 
                                </tr>
                
                                <tr>
                                        <td>Non Occupancy Charges</td>
                                        <td class="text-right">0.00</td> 
                                </tr>
                
                                <tr>
                                        <td>Additional Items</td>
                                        <td class="text-right">0.00</td> 
                                </tr>
                
                                <tr>
                                        <td>Additional Items</td>
                                        <td class="text-right">0.00</td> 
                                </tr>
                
                                <tr class="table-info">
                                        <td class="text-right"><strong>TOTAL</strong></td>
                                        <td class="text-right"><strong>5799.00</strong></td> 
                                </tr>
                
                            </table>
                        
                            </div>
                            
                        <div>
    
        
                            <form method="POST" action="">
                                
                                <input type='hidden' name='csrfmiddlewaretoken' value='ywagsmi0RgOlzx3Icj594JHtJ3JN2M6ibpz3QNDCE9dEq91C2UR1hSRiNmPwxK2Q' />
                                
                                    <p><label for="id_paid_on">Paid on:</label> 
                                       <input type="text" name="paid_on" required id="id_paid_on" class="form-control"/>
                                    </p>
                               
                                <p><label for="id_payment_mode">Payment mode:</label>
                                    <input type="text" name="payment_mode" maxlength="200" required id="id_payment_mode" class="form-control" /> <span class="helptext">Cheque, Bank Transfer etc.</span>
                                </p>
                                <p><label for="id_drawn_on">Drawn on:</label>
                                    <input type="text" name="drawn_on" maxlength="250" required id="id_drawn_on" class="form-control" /> <span class="helptext">Financial institution received from.</span>
                                </p>
                                <p><label for="id_transaction_no">Transaction no:</label>
                                    <input type="text" name="transaction_no" maxlength="250" required id="id_transaction_no" class="form-control" /> <span class="helptext">Cheque Number or Bank Transfer Number.</span>
                                </p>
                                <p><label for="id_received_amount">Received amount:</label> 
                                    <input type="number" name="received_amount" value="5573.00" step="0.01" required id="id_received_amount" class="form-control" /> <span class="helptext">Amount Received from Member.</span>
                                </p>
                                <button class="btn waves-effect waves-light right" type="submit" name="action">Submit</button>
                                
                            </form>
                        
                    
            
                
            
                            </div>
                            
                </div>
            </div> 
        </div>           
        
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        </script>
    </body>
    </html>